### ISSUE TITLE
How are we doing?

### ISSUE THREAD

**Issue by davidpdrsn** [davidpdrsn/CardistryIO#152]
# 🎉🎉 Cardistry Con is one week 🎉🎉

At the moment I have [8 issues assigned to me with the Cardistry Con milestone](https://github.com/davidpdrsn/CardistryIO/issues?q=is:open+milestone:"Cardistry+Con+2016"+assignee:davidpdrsn) and [Ben you have 11](https://github.com/davidpdrsn/CardistryIO/issues?q=is:open+milestone:"Cardistry+Con+2016"+assignee:bendobos) however yours seems to be quite big.

I do imagine I'll be able to close most of my issues before Cardistry Con. How are you feeling about yours? If you don't think you'll make it that is totally okay. I feel like we're in a state where we can at least show people that we're not joking around. And I think that is the most important thing.

I would honestly also feel more comfortable launching while I'm sitting in front of my computer and can deal the issues that might happen.

I'll also start writing the talk soon so expect an issue about that within the next few days.

@bendobos

**Comment by bendobos** [comment]
There is still a lot to do but I am pretty confident that we will have a version that people can use in a week. 
But I agree - maybe it will be better to get people hyped up first. We can then take our time to ship a product that is actually reads for prime time. And I think in order to be successful, it needs to be awesome else people will fall back to Instagram or the likes. 
We could also consider a "friends & family beta", just for the people at CC. We should use this opportunity to gather feedback and maybe some ideas from the community. 

I am also of the opinion that a great mobile experience with maybe even an app is essential for our success. While we will have a mobile version, it will be very barebones. I would love to take a week or two and build a real hybrid app with something like Ionic.

**Comment by bendobos** [comment]
Oh and if you need any assets designed to make the talk look awesome, let me know!

**Comment by davidpdrsn** [comment]
I agree. I also think mobile is where its at we once we've proven our case we to think about that.

And I expect CC will generate lots of hype and lots of people are gonna wanna join and contribute the initial content. Excited to see how it goes and good to hear you're still optimistic.

**Comment by corroded** [comment]
If you guys need any help in styling I can code up some SCSS as well. I'm not much of a design person but a few years back I was a frontend coder so I can pretty much splice up some PSDs or Zeplin stuff. So I won't get in the way of the design, but I can help in hammering out the CSS/HAML you need :) 

Also, I think I saw in reddit that someone was also doing a [mobile app](https://www.reddit.com/r/cardistry/comments/4nbpcc/hints_of_a_new_cardistry_app_from_cardistry_touch/)? It may be different, or it may be the same so I suggest to double check first. (Okay, looked through the comments, it's this: http://tenmoves.net/)

**Comment by lpalmes** [comment]
@corroded Yep, that's david's app, ten moves, but i'm not so sure about my shuffles, i think that's the same idea but developed for android.

**Comment by corroded** [comment]
Haha obviously I didn't bother to check the contact. So embarrassing 😨

**Comment by davidpdrsn** [comment]
I'll let @bendobos decide if and how @corroded can help.

And I did actually talk briefly with Dimitri about their app. Don't think it's gonna be like the what I made though.

**Comment by bendobos** [comment]
I've almost finished the profile page and the "watch video" screen is next up for me. 

Any help is greatly appreciated at this point! 

@corroded It would be really cool if you could wire up the list views (list videos, search results etc). I don't have a design for that but I don't find it's necessary since this is a pretty simple "no-frills" view, so you are pretty free there!

**Comment by corroded** [comment]
sweet. is there an issue in GH you can assign it to me to? Anyway, sure will work on that as well 👍
