### ISSUE TITLE
Teaser

### ISSUE THREAD

**Issue by bendobos** [davidpdrsn/CardistryIO#5]
I'm still not so sure about not having a teaser page. My points why I think it is important:
- We get some coverage immediately. People will be hyped, check back every day and so on.
- We get already gather some intel. Like for example which browsers we need to support.
- It will look cool and will be better than a password-prompt when you visit cardistry.io

Points I see challenges in:
- We need to make sure to have all names and domains secure, just in case someone wants to be an asshole.

Other than that, I see no disadvantage in having a teaser page. What's your reasoning behind not wanting a teaser page?
In reality, this right here already is a kind of teaser, just one not everyone understands...

**Comment by davidpdrsn** [comment]
There are few reasons why I don't think making a teaser/landing page is a good idea
- It forces us to actually deliver something. I have no doubts that we'll build a really awesome thing and that everything will work out. But if something happens that makes us be late or never actually finish then we don't have to explain much, because we're not committed to shipping.
- We don't know exactly when we'll ship. If we put out a teaser page and people see it now and we don't ship for another few months I think people will loose interest. I would rather take people by surprise.
- I think our time is better spent building the product itself.

I got these ideas from companies like [thoughtbot](https://thoughtbot.com/) and [Basecamp](https://basecamp.com/).

You're right that this page might be a teaser (or more a spoiler) but I doubt anyone from the Cardistry community is gonna find it.

And about browsers I say IE 10+ and the latest + previous version of the rest. That should keep us covered.
