### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by bendobos** [davidpdrsn/CardistryIO#7]
Two issues I ran into:
- Is it possible to lay out the notification to have three different elements `notification.user_avatar`, `notification.user_name` and `notification.text`? That way, I could make the notification dropdown look cooler.
- Maybe I did something wrong in my dropdown implementation but old notifications that have been marked as read are not permanentlly destroyed. I noticed that it works in the notification view you made. Maybe you could take a look at `app/views/application/_buttonbar.haml:61` and tell me what I did wrong :)

**Comment by davidpdrsn** [comment]
You can do `notification.user.username` and so on. If you want the user that triggered the notification you can do `notification.actor`, that'll return a user as well. If you want the thing that the notification is about you can do `notification.subject`. See more in "app/models/notification.rb".

And yeah the bug with notifications not going away has been fixed on master. You can rebase in master and you'll get the fixes.

**Comment by davidpdrsn** [comment]
I've made some changes to notifications in order to get mentions to work correctly. Now, if you need the text for a notification you have write `notification.text.expand`.
This is because of the way mentions are done where the notification text includes a link to the thing you're being notified about.

The text definition for mention notifications look like this

``` ruby
"@#{actor.username} mentioned you in a {{link}}"
```

And so you can provide the link later by doing `notification.text.expand(link: "foobar")`.

You shouldn't need to worry too much about this however :smile:
